#!/usr/bin/env sh

# Format modified files
prettier $(git diff --cached --name-only --diff-filter=ACMR | grep -e ".ts$" | sed 's| |\\ |g') --write --ignore-unknown

# Update index with modified files
git update-index --again

# Run lint on modified files
eslint $(git diff --cached --name-only --diff-filter=ACMR | grep -e ".ts$" | sed 's| |\\ |g')

# Update index with modified files
git update-index --again
