name: Node.js CI

on:
    push:
        branches: [main, dev]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build
            - run: npm run lint
            - run: npm run format:check
            - run: npm test

    build_pre_workspaces:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i -g npm@7
            - run: npm ci
            - run: npm run build
            - run: npm run lint
            - run: npm run format:check
            - run: npm test
